
ASM_FILES	:= 

C_FILES 	:= 

CPP_FILES       :=  nand_ecc.cpp  nand_menu.cpp  s3c2410.cpp nand_base.cpp   nand.cpp      nand_ids.cpp  s3c2440.cpp s3c6410.cpp

SUBDIRS	:=

include $(TOPDIR)/Rules.make
