
ASM_FILES	:= 

C_FILES 	:= 

CPP_FILES       := jtag.cpp  mem_rdwr.cpp  s3c2410_mem_rdwr.cpp  s3c2440_mem_rdwr.cpp s3c6410_mem_rdwr.cpp interface.cpp

SUBDIRS	:= openjtag/ dongle/ wiggler/

include $(TOPDIR)/Rules.make
